server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/petOne
    username: petonedb
    password: P3t@Ne2024!

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.19:8080/realms/petone
          jwk-set-uri: http://192.168.56.19:8080/realms/petone/protocol/openid-connect/certs

  oauth2:
    client:
      registration:
        keycloak:
          client-id: petone
          client-secret: 90URn6CkWsS2ctgvpssIjSPc2ell3A7q
          scope: openid profile email
      provider:
        keycloak:
          authorization-uri: http://192.168.56.19:8080/realms/petone/protocol/openid-connect/auth
          token-uri: http://192.168.56.19:8080/realms/petone/protocol/openid-connect/token
          user-info-uri: http://192.168.56.19:8080/realms/petone/protocol/openid-connect/userinfo
          jwk-set-uri: http://192.168.56.19:8080/realms/petone/protocol/openid-connect/certs
          issuer-uri: http://192.168.56.19:8080/realms/petone
